---
# This playbook deploys the whole demo enviroment.

- name: Build hosts inventory in memory for localhost
  hosts: localhost
  gather_facts: no
  vars_files:
  - group_vars/mds_var.yml
  - group_vars/sm_var.yml
  - group_vars/smsg_var.yml
  - group_vars/sg_var.yml
  roles:
    - role: inventory
      tags: [ "always" ]
      
- name: Deploy a virtual machine as Security Management Server and Security Gateway
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/smsg_var.yml
  roles:
    - role: vmrun
      tags: [ "prepp-demo" ]

- name: Configure Gaia OS on Security Management Server and Security Gateway
  hosts: 
  - "{{ target }}"
  - "{{ groups['gaia_template'][0] }}"
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/smsg_var.yml
  roles:
    - role: gaia
      tags: [ "prepp-demo" ]

- name: Configure Security Management Server and Security Gateway using The R80.x Security Management API
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/smsg_var.yml
  - fingerprints/smsg_finger.yml
  roles:
    - role: r80api
      mgmt_fingerprint: "{{ hostvars[groups['smsg'][0]]['mgmt_fingerprint'] }}"
    - role: r80api
      tags: [ "never", "sg-demo" ]
#      mgmt_fingerprint: "{{ hostvars[groups['smsg'][0]]['mgmt_fingerprint'] }}"

- name: Deploy our E-comerce web server
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - role: vmrun
    tags: [ "never", "sg-demo", "webserver" ]
    hostname: WebServer
    type: webserver